// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: kit
  static const package = "kit";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/btn_check_off.png
  // ignore: non_constant_identifier_names
  final btn_check_off =
      const AssetResource("assets/images/btn_check_off.png", packageName: null);

  /// asset: assets/images/btn_check_on.png
  // ignore: non_constant_identifier_names
  final btn_check_on =
      const AssetResource("assets/images/btn_check_on.png", packageName: null);

  /// asset: assets/images/btn_photo_blue.png
  // ignore: non_constant_identifier_names
  final btn_photo_blue = const AssetResource("assets/images/btn_photo_blue.png",
      packageName: null);

  /// asset: assets/images/btn_send.png
  // ignore: non_constant_identifier_names
  final btn_send =
      const AssetResource("assets/images/btn_send.png", packageName: null);

  /// asset: assets/images/event_detail_img.png
  // ignore: non_constant_identifier_names
  final event_detail_img = const AssetResource(
      "assets/images/event_detail_img.png",
      packageName: null);

  /// asset: assets/images/event_list_img.png
  // ignore: non_constant_identifier_names
  final event_list_img = const AssetResource("assets/images/event_list_img.png",
      packageName: null);

  /// asset: assets/images/head_btn_back.png
  // ignore: non_constant_identifier_names
  final head_btn_back =
      const AssetResource("assets/images/head_btn_back.png", packageName: null);

  /// asset: assets/images/head_btn_back_white.png
  // ignore: non_constant_identifier_names
  final head_btn_back_white = const AssetResource(
      "assets/images/head_btn_back_white.png",
      packageName: null);

  /// asset: assets/images/head_btn_close.png
  // ignore: non_constant_identifier_names
  final head_btn_close = const AssetResource("assets/images/head_btn_close.png",
      packageName: null);

  /// asset: assets/images/head_btn_close_wh.png
  // ignore: non_constant_identifier_names
  final head_btn_close_wh = const AssetResource(
      "assets/images/head_btn_close_wh.png",
      packageName: null);

  /// asset: assets/images/head_btn_search.png
  // ignore: non_constant_identifier_names
  final head_btn_search = const AssetResource(
      "assets/images/head_btn_search.png",
      packageName: null);

  /// asset: assets/images/i_calendar.png
  // ignore: non_constant_identifier_names
  final i_calendar =
      const AssetResource("assets/images/i_calendar.png", packageName: null);

  /// asset: assets/images/i_profile.png
  // ignore: non_constant_identifier_names
  final i_profile =
      const AssetResource("assets/images/i_profile.png", packageName: null);

  /// asset: assets/images/login_i_03.png
  // ignore: non_constant_identifier_names
  final login_i_03 =
      const AssetResource("assets/images/login_i_03.png", packageName: null);

  /// asset: assets/images/login_i_04.png
  // ignore: non_constant_identifier_names
  final login_i_04 =
      const AssetResource("assets/images/login_i_04.png", packageName: null);

  /// asset: assets/images/login_i_05.png
  // ignore: non_constant_identifier_names
  final login_i_05 =
      const AssetResource("assets/images/login_i_05.png", packageName: null);

  /// asset: assets/images/login_i_06.png
  // ignore: non_constant_identifier_names
  final login_i_06 =
      const AssetResource("assets/images/login_i_06.png", packageName: null);

  /// asset: assets/images/radio_off.png
  // ignore: non_constant_identifier_names
  final radio_off =
      const AssetResource("assets/images/radio_off.png", packageName: null);

  /// asset: assets/images/radio_on.png
  // ignore: non_constant_identifier_names
  final radio_on =
      const AssetResource("assets/images/radio_on.png", packageName: null);

  /// asset: assets/images/web_hi_res_512.png
  // ignore: non_constant_identifier_names
  final web_hi_res_512 = const AssetResource("assets/images/web_hi_res_512.png",
      packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/btn_check_off.png
  // ignore: non_constant_identifier_names
  AssetImage btn_check_off() {
    return AssetImage(asset.btn_check_off.keyName);
  }

  /// asset: assets/images/btn_check_on.png
  // ignore: non_constant_identifier_names
  AssetImage btn_check_on() {
    return AssetImage(asset.btn_check_on.keyName);
  }

  /// asset: assets/images/btn_photo_blue.png
  // ignore: non_constant_identifier_names
  AssetImage btn_photo_blue() {
    return AssetImage(asset.btn_photo_blue.keyName);
  }

  /// asset: assets/images/btn_send.png
  // ignore: non_constant_identifier_names
  AssetImage btn_send() {
    return AssetImage(asset.btn_send.keyName);
  }

  /// asset: assets/images/event_detail_img.png
  // ignore: non_constant_identifier_names
  AssetImage event_detail_img() {
    return AssetImage(asset.event_detail_img.keyName);
  }

  /// asset: assets/images/event_list_img.png
  // ignore: non_constant_identifier_names
  AssetImage event_list_img() {
    return AssetImage(asset.event_list_img.keyName);
  }

  /// asset: assets/images/head_btn_back.png
  // ignore: non_constant_identifier_names
  AssetImage head_btn_back() {
    return AssetImage(asset.head_btn_back.keyName);
  }

  /// asset: assets/images/head_btn_back_white.png
  // ignore: non_constant_identifier_names
  AssetImage head_btn_back_white() {
    return AssetImage(asset.head_btn_back_white.keyName);
  }

  /// asset: assets/images/head_btn_close.png
  // ignore: non_constant_identifier_names
  AssetImage head_btn_close() {
    return AssetImage(asset.head_btn_close.keyName);
  }

  /// asset: assets/images/head_btn_close_wh.png
  // ignore: non_constant_identifier_names
  AssetImage head_btn_close_wh() {
    return AssetImage(asset.head_btn_close_wh.keyName);
  }

  /// asset: assets/images/head_btn_search.png
  // ignore: non_constant_identifier_names
  AssetImage head_btn_search() {
    return AssetImage(asset.head_btn_search.keyName);
  }

  /// asset: assets/images/i_calendar.png
  // ignore: non_constant_identifier_names
  AssetImage i_calendar() {
    return AssetImage(asset.i_calendar.keyName);
  }

  /// asset: assets/images/i_profile.png
  // ignore: non_constant_identifier_names
  AssetImage i_profile() {
    return AssetImage(asset.i_profile.keyName);
  }

  /// asset: assets/images/login_i_03.png
  // ignore: non_constant_identifier_names
  AssetImage login_i_03() {
    return AssetImage(asset.login_i_03.keyName);
  }

  /// asset: assets/images/login_i_04.png
  // ignore: non_constant_identifier_names
  AssetImage login_i_04() {
    return AssetImage(asset.login_i_04.keyName);
  }

  /// asset: assets/images/login_i_05.png
  // ignore: non_constant_identifier_names
  AssetImage login_i_05() {
    return AssetImage(asset.login_i_05.keyName);
  }

  /// asset: assets/images/login_i_06.png
  // ignore: non_constant_identifier_names
  AssetImage login_i_06() {
    return AssetImage(asset.login_i_06.keyName);
  }

  /// asset: assets/images/radio_off.png
  // ignore: non_constant_identifier_names
  AssetImage radio_off() {
    return AssetImage(asset.radio_off.keyName);
  }

  /// asset: assets/images/radio_on.png
  // ignore: non_constant_identifier_names
  AssetImage radio_on() {
    return AssetImage(asset.radio_on.keyName);
  }

  /// asset: assets/images/web_hi_res_512.png
  // ignore: non_constant_identifier_names
  AssetImage web_hi_res_512() {
    return AssetImage(asset.web_hi_res_512.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: nanum
  // ignore: non_constant_identifier_names
  final nanum = "nanum";
}
